---

# tasks file for osp.servers

- name: instance frontend
  include: ospinstance.yml
  vars:
    myinstance: "{{osp_servers.frontend}}"

- name: instance app1
  include: ospinstance.yml
  vars:
    myinstance: "{{osp_servers.app1}}"

- name: instance app2
  include: ospinstance.yml
  vars:
    myinstance: "{{osp_servers.app2}}"

- name: instance db
  include: ospinstance.yml
  vars:
    myinstance: "{{osp_servers.db}}"

